### ISSUE TITLE
history graph

### ISSUE THREAD

**Issue by sshah402** [Team-DOFH-2340/2340-Project#11]
when the option for history is chosen, view in main app will change to this scene (available for managers and higher entities)

enter a location, either virus or contaminant, and a year. The system will then display an XY graph where the X axis is the month and the Y axis is the PPM. Each month's data point can be an average of the reports for that month if there are more than one.

**Comment by kberzinch** [comment]
I figured out how to put stuff on the graph and how to filter stuff we don't want, and built a search criteria UI. I think I need to pass info to the controller before it initializes, but I don't know of any good way to do that. Feel free to call me if you want more info, sending phone number in DM.
